basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: This is a sample server for a pet store.
  termsOfService: http://swagger.io/terms/
  title: Swagger Example API
  version: "1.0"
paths: {}
swagger: "2.0"
