services:
  golang:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    container_name: golang
    env_file:
      - .env
  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
