name: Terraform CI/CD

on:
  push:
    branches:
      - "feat/cd"
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Validate Terraform Configuration
        run: terraform validate
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        working-directory: ./terraform

      - name: Retrieve Private Key from Terraform Output
        id: get_private_key
        run: |
          {
          echo 'PRIVATE_KEY<<EOF'
          terraform output private_key
          echo 'EOF'
          } >> %GITHUB_ENV
          echo "public_ip=$(terraform output public_ip)" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Set environment variables from Terraform output
        run: |
          echo "PRIVATE_KEY=${{ steps.get_private_key.outputs.private_key }}" >> $GITHUB_ENV
          echo "PUBLIC_IP=${{ steps.get_private_key.outputs.public_ip }}" >> $GITHUB_ENV
        working-directory: ./terraform

      - name: Deploy Script to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ env.PUBLIC_IP }}
          username: ubuntu
          key: ${{ env.PRIVATE_KEY }}
          port: 22
          script: |
            sudo mv /tmp/script.sh /home/ubuntu/
            sudo chmod +x /home/ubuntu/script.sh
            sudo /home/ubuntu/script.sh

      - name: Destroy Infrastructure (Optional)
        if: github.event_name == 'pull_request'
        run: |
          cd terraform
          terraform destroy -auto-approve
