name: Terraform CI/CD

on:
  push:
    branches:
      - "feat/cd"
  pull_request:
    branches:
      - main
      - dev

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0

      - name: Configure AWS credentials
        env:
          TF_VAR_acces_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          TF_VAR_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: echo "AWS credentials configured"

      - name: Initialize Terraform
        run: |
          cd terraform
          terraform init

      - name: Validate Terraform Configuration
        run: |
          cd terraform
          terraform validate

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -out=tfplan

      - name: Apply Terraform Changes
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          cd terraform
          terraform apply -auto-approve tfplan

      - name: Retrieve Private Key from Terraform Output
        id: get_private_key
        run: |
          cd terraform
          echo "name=private_key >> $(terraform output -raw private_key_pem)"

      - name: Deploy Script to VM
        uses: appleboy/ssh-action@master
        with:
          host: ${{ steps.terraform.outputs.public_ip }}
          username: ubuntu # Replace with your instance's SSH username
          key: ${{ steps.get_private_key.outputs.private_key }}
          port: 22
          script: |
            sudo mv /tmp/script.sh /home/ubuntu/
            sudo chmod +x /home/ubuntu/script.sh
            sudo /home/ubuntu/script.sh

      - name: Destroy Infrastructure (Optional)
        if: github.event_name == 'pull_request'
        run: |
          cd terraform
          terraform destroy -auto-approve
