name: Pipeline CI

on:
  push:
    branches:
      - main
      - dev
      - feat/test
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Back

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the docker-compose
        run: docker compose up -d
        if: success()

      - name: Check golang container logs
        run: |
          sleep 5
          docker-compose logs golang
          docker-compose logs postgres
        


      - name: Run tests inside the container
        run: |
          docker-compose exec golang go test tests/utils.go tests/register_test.go
          docker-compose exec golang go test tests/utils.go tests/login_test.go
          docker-compose exec golang go test tests/utils.go tests/colocation_test.go

