name: Pipeline CI

on:
  push:
    branches:
      - main
      - dev
      - feat/test
  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: Back

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run the docker-compose
        run: docker compose up -d
        working-directory: Back
        if: success()

      - name: Run tests inside the container
        run: |
          docker exec golang go test ./tests/register_test.go
          docker exec golang go test ./tests/login_test.go
          docker exec golang go test ./tests/colocation_test.go
